= Dotfile management

:keywords: sysadmin, dotfiles, git

https://news.ycombinator.com/item?id=11071754[This HN comment] (referenced
https://lobste.rs/s/azw1gx/manage_your_dotfiles_with_git[here]) has a technique
for managing dotfiles. The comment is:

____
I use:

    git init --bare $HOME/.myconf
    alias config='/usr/bin/git --git-dir=$HOME/.myconf/ --work-tree=$HOME'
    config config status.showUntrackedFiles no

where my ~/.myconf directory is a git bare repository. Then any file within the home folder can be versioned with normal commands like:

    config status
    config add .vimrc
    config commit -m "Add vimrc"
    config add .config/redshift.conf
    config commit -m "Add redshift config"
    config push

And so on... extra tooling, no symlinks, files are tracked on a version control system, you can use different branches for different computers, you can replicate you configuration easily on new installation.
____

seems strictly better than using home-manager, as the files it manages are
read-only which makes iterating on them painful.

To set this up on a fresh computer:

----
git init --bare $HOME/.dotfiles
alias config='/etc/profiles/per-user/$(whoami)/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
config config status.showUntrackedFiles no
config remote add origin https://github.com/gunnihinn/dotfiles.git
config fetch
config checkout origin/master -ft
----
